name: Build & Submit Production

on:
  pull_request:
    branches: [main] # Target branch is 'main'
    paths-ignore: ["docs/**"]
    types: [opened, reopened] # Avoid triggering on new commits

jobs:
  build:
    if: github.head_ref == 'dev' # Only run if PR is from 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: 16.1.0
          token: ${{ secrets.EAS_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Trigger Android Production Build
        run: eas build --platform android --profile production --non-interactive --no-wait

      # - name: Trigger iOS Production Build
      #   run: eas build --platform ios --profile production --non-interactive --no-wait

      - name: Submit Android Build to Store
        run: eas submit --platform android --profile production --non-interactive

      # - name: Submit iOS Build to Store
      #   run: eas submit --platform ios --profile production --non-interactive
