name: OTA Publish to Production

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]
jobs:
  publish-ota:
    if: startsWith(github.head_ref, 'ota/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: 16.1.0
          token: ${{ secrets.EAS_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Publish OTA to Production Channel
        run: eas update --channel production --platform android --non-interactive
